---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ibrokhi1/games.droplet.uz/
    - /bin/cp -R build/static $DEPLOYPATH
    - /bin/cp build/asset-manifest.json $DEPLOYPATH
    - /bin/cp build/favicon.ico $DEPLOYPATH
    - /bin/cp build/index.html $DEPLOYPATH
    - /bin/cp build/logo.png $DEPLOYPATH
    - /bin/cp build/logo2.png $DEPLOYPATH
    - /bin/cp build/logo3.ico $DEPLOYPATH
    - /bin/cp build/manifest.json $DEPLOYPATH
    - /bin/cp build/robots.txt $DEPLOYPATH
